client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu: randomL1A
  delayScanData_port: '8889'
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  elinks_trg:
  - idcode: 0
    name: link0
    polarity: 0
  - idcode: 2
    name: link1
    polarity: 1
  - idcode: 3
    name: link2
    polarity: 1
  - idcode: 1
    name: link3
    polarity: 0
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: '8888'
metaData:
  Channel_off: []
  characMode: 1
  chip_params: {}
  hexactrl: 10.254.56.32
  hw_type: 1ROC
  keepRawData: 1
  keepSummary: 1
  testName: pedestal_run
roc_s0:
  sc:
    DigitalHalf:
      0: 
        L1Offset: 10
        Bx_offset: 2
        CalibrationSC: 1
        SelTC4: 1
      1: 
        L1Offset: 10
        Bx_offset: 2
        CalibrationSC: 1
        SelTC4: 1
    GlobalAnalog:
      0:
        Delay9: 3 #3
        Delay87: 3 #3
        Delay65: 3 #3
        Delay40: 2 #2
        Idac_inv: 6 # 4 default, 6
        Idac_tot: 6 # 4 default, 6
        Ref_pa_cm: 0 # 3 default, 0=150mV, 1=2=200mV, 3=250mV, 0
        ON_backup: 0 # 1 default: 0 = enable compensation with common mode channel
        ON_conv: 1 # '1': enable conveyor bias
        SelExtADC: 0 # 1 default, 0
        SelRisingEdge: 1
        Dacb_dynran: 3 # 3 default, 0
        Gain_conv: 8 #8 links
        Cd: 0 # 7 default, 4
        Cf_comp: 10 # 10 default, 1
        Cf: 10 # 10 default, 1
        Rf: 12 # 8 default
        Dacb_vbi_pa: 32 # 32 default
        Dacb_vb_conv: 6 # 6 default
      1:
        Delay9: 3 #3
        Delay87: 3 #3
        Delay65: 3 #3
        Delay40: 2 #2
        Idac_inv: 6 # 4 default, 6
        Idac_tot: 6 # 4 default, 6
        Ref_pa_cm: 0 # 3 default, 0=150mV, 1=2=200mV, 3=250mV,0
        ON_backup: 0 # 1 default, 0 = enable compensation with common mode channel
        ON_conv: 1 # '1': enable conveyor bias
        SelExtADC: 0 # 1 default, 0 before
        SelRisingEdge: 1
        Dacb_dynran: 3 # 3 default, 0
        Gain_conv: 8 #8 rechts
        Cd: 0 # 7 default
        Cf_comp: 10 # 10 default
        Cf: 10 # 10 default
        Rf: 12 # 8 default
        Dacb_vbi_pa: 32 # 32 default
        Dacb_vb_conv: 6 # 6 default
    ReferenceVoltage:
      0:
        Vbg_1v: 3 # 5 default, 3
        Refi: 1 # 3 default, 1
        choice_cinj: 0 # O default
        cmd_120p: 0 # 0 default
        Calib_2V5: 0 
        Inv_vref: 550 #was 550, def 256
        Noinv_vref: 850 #was 850, def 316
        Tot_vref: 550 # was 678   500, 1000
        Toa_vref: 350 # was 200   200, 1000
      1:
        Vbg_1v: 3 # 5 default, 3
        Refi: 1 # 3 default, 1
        choice_cinj: 0 # O default
        cmd_120p: 0 # 0 default
        Calib_2V5: 0 
        Inv_vref: 550 #was 550, def 256
        Noinv_vref: 850 #was 850, def 316
        Tot_vref: 550 # was 678    500, 1000
        Toa_vref: 400 # was 200   200, 1000
    MasterTdc: 
      all:
        BIAS_I_CTDC_D: 10 # 24 by default
        FOLLOWER_CTDC_EN: 1 # 1 by default
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1 # 0 by default
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4 # 0 by default
        GLOBAL_EN_BUFFER_CTDC: 1 # 0 by default
        BIAS_CAL_DAC_CTDC_P_EN: 1 # 0 by default
        BIAS_CAL_DAC_CTDC_P_D: 2 # 0 by default
        BIAS_I_FTDC_D: 10 # 24 by default
        FOLLOWER_FTDC_EN: 1 # 1 by default
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1 # 0 by default
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4 # 0 by default
        GLOBAL_EN_BUFFER_FTDC: 1 # 0 by default
        CTDC_CALIB_FREQUENCY: 2 # 2 by default
        FTDC_CALIB_FREQUENCY: 2 # 2 by default
      #0:
        #CTRL_IN_REF_CTDC_P_D: 25 # 0 by default
        #CTRL_IN_REF_CTDC_P_EN: 1 # 0 by default
      #1: 
        #CTRL_IN_REF_CTDC_P_D: 15 # 0 by default
        #CTRL_IN_REF_CTDC_P_EN: 1 # 0 by default
    Top:
      all:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        ENpE: 0 # pre-emphasis. 3bits, ENpE0, pE1, pE2. Default 0. Set 500uA, 1mA, 2mA 
        S: 0     # width of pre-emphasis pulse, 2bit. Default 0. width at 0 is not zero. 
    calib:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 0
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 0
    ch:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      4:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      5:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      6:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      7:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      8:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      9:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      10:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      11:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      12:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      13:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      14:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      15:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      16:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      17:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      18:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      19:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      20:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      21:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      22:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      23:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      24:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      25:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      26:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      27:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      28:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      29:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      30:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      31:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      32:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      33:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      34:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31 
      35:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      36:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      37:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      38:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      39:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      40:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      41:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      42:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      43:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      44:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      45:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      46:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      47:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      48:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      49:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
      50:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      51:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      52:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      53:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      54:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      55:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      56:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      57:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      58:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      59:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      60:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
      61:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      62:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      63:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      64:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      65:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      66:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      67:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      68:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      69:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      70:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      71:
        Gain_conv: 0
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
    cm:
      0:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      1:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      2:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
      3:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
