client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: /home/hgcal/Desktop/software_test_Jia-Hao/hexactrl-sw/hexactrl-script_TB_23_08/data/TB3_D8_ps1_Feb2024/pedestal_run/run_20240210_101726__trimmed_vrefinv_trimmed/
  run_type: pedestal_run
  serverIP: tbtester1
daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu: randomL1A
  delayScanData_port: '8889'
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  elinks_trg:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 2
    name: link2
    polarity: 1
  - idcode: 3
    name: link3
    polarity: 1
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 0
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: '8888'
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        L1Offset: 10
    GlobalAnalog:
      0:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
      1:
        Cd: 0
        Cf: 10
        Cf_comp: 10
        Dacb_dynran: 3
        Dacb_vb_conv: 6
        Dacb_vbi_pa: 32
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Gain_conv: 0
        Idac_inv: 6
        Idac_tot: 6
        ON_backup: 0
        ON_conv: 1
        Ref_pa_cm: 0
        Rf: 12
        SelExtADC: 0
        SelRisingEdge: 1
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Calib_2V5: 0
        Inv_vref: 695
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 900
        Tot_vref: 1000
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
      1:
        Calib_2V5: 0
        Inv_vref: 664
        Noinv_vref: 850
        Refi: 1
        Toa_vref: 900
        Tot_vref: 1000
        Vbg_1v: 3
        choice_cinj: 0
        cmd_120p: 0
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
    calib:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
    ch:
      0:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 45
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 31
        trim_tot: 31
      2:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 51
        trim_toa: 31
        trim_tot: 31
      3:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 31
        trim_tot: 31
      4:
        Gain_conv: 4
        Inputdac: 31
        dacb: 4
        sign_dac: 1
        trim_inv: 9
        trim_toa: 31
        trim_tot: 31
      5:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 31
        trim_tot: 31
      6:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 39
        trim_toa: 31
        trim_tot: 31
      7:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 29
        trim_toa: 31
        trim_tot: 31
      8:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 22
        trim_toa: 31
        trim_tot: 31
      9:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 34
        trim_toa: 31
        trim_tot: 31
      10:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 38
        trim_toa: 31
        trim_tot: 31
      11:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
        trim_toa: 31
        trim_tot: 31
      12:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 29
        trim_toa: 31
        trim_tot: 31
      13:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 39
        trim_toa: 31
        trim_tot: 31
      14:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 24
        trim_toa: 31
        trim_tot: 31
      15:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 27
        trim_toa: 31
        trim_tot: 31
      16:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 20
        trim_toa: 31
        trim_tot: 31
      17:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 31
        trim_tot: 31
      18:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 12
        trim_toa: 31
        trim_tot: 31
      19:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 22
        trim_toa: 31
        trim_tot: 31
      20:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 48
        trim_toa: 31
        trim_tot: 31
      21:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 16
        trim_toa: 31
        trim_tot: 31
      22:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 31
        trim_tot: 31
      23:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 39
        trim_toa: 31
        trim_tot: 31
      24:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 23
        trim_toa: 31
        trim_tot: 31
      25:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 41
        trim_toa: 31
        trim_tot: 31
      26:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 31
        trim_tot: 31
      27:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 37
        trim_toa: 31
        trim_tot: 31
      28:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 40
        trim_toa: 31
        trim_tot: 31
      29:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 31
        trim_tot: 31
      30:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 31
        trim_tot: 31
      31:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 38
        trim_toa: 31
        trim_tot: 31
      32:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 30
        trim_toa: 31
        trim_tot: 31
      33:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 24
        trim_toa: 31
        trim_tot: 31
      34:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 9
        trim_toa: 31
        trim_tot: 31
      35:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 50
        trim_toa: 31
        trim_tot: 31
      36:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 31
        trim_tot: 31
      37:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 28
        trim_toa: 31
        trim_tot: 31
      38:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 15
        trim_toa: 31
        trim_tot: 31
      39:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 46
        trim_toa: 31
        trim_tot: 31
      40:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 25
        trim_toa: 31
        trim_tot: 31
      41:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      42:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 32
        trim_toa: 31
        trim_tot: 31
      43:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 23
        trim_toa: 31
        trim_tot: 31
      44:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      45:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 42
        trim_toa: 31
        trim_tot: 31
      46:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 0
        trim_toa: 31
        trim_tot: 31
      47:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 31
        trim_tot: 31
      48:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 36
        trim_toa: 31
        trim_tot: 31
      49:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
      50:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 56
        trim_toa: 31
        trim_tot: 31
      51:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 38
        trim_toa: 31
        trim_tot: 31
      52:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 43
        trim_toa: 31
        trim_tot: 31
      53:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 20
        trim_toa: 31
        trim_tot: 31
      54:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 51
        trim_toa: 31
        trim_tot: 31
      55:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 30
        trim_toa: 31
        trim_tot: 31
      56:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 56
        trim_toa: 31
        trim_tot: 31
      57:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 30
        trim_toa: 31
        trim_tot: 31
      58:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
        trim_toa: 31
        trim_tot: 31
      59:
        Gain_conv: 4
        Inputdac: 31
        dacb: 2
        sign_dac: 0
        trim_inv: 58
        trim_toa: 31
        trim_tot: 31
      60:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 21
      61:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 35
        trim_toa: 31
        trim_tot: 31
      62:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 39
        trim_toa: 31
        trim_tot: 31
      63:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      64:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 45
        trim_toa: 31
        trim_tot: 31
      65:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 26
        trim_toa: 31
        trim_tot: 31
      66:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 45
        trim_toa: 31
        trim_tot: 31
      67:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 38
        trim_toa: 31
        trim_tot: 31
      68:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 53
        trim_toa: 31
        trim_tot: 31
      69:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 19
        trim_toa: 31
        trim_tot: 31
      70:
        Gain_conv: 4
        Inputdac: 31
        dacb: 0
        sign_dac: 0
        trim_inv: 62
        trim_toa: 31
        trim_tot: 31
      71:
        Gain_conv: 0
        Inputdac: 31
        dacb: 2
        sign_dac: 1
        trim_inv: 1
        trim_toa: 31
        trim_tot: 31
    cm:
      0:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      1:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      2:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
      3:
        Gain_conv: 4
        Inputdac: 0
        dacb: 0
        sign_dac: 0
        trim_inv: 31
        trim_toa: 31
        trim_tot: 31
